[build]
  # The directory where Netlify will run the build command
  base = "cd pwaapp"
  
  # The command to run to build your site
  command = "npm run build"
  
  # The directory (relative to the base) that contains the deploy-ready files
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

# This handles routing for single page applications like React
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
